# Dockerfile for account-manager and payment-manager
FROM node:16

# Create app directory
WORKDIR / payment-manager

RUN node -v
# Install app dependencies
COPY package*.json ./

RUN npm install

# Check Node.js version
RUN node -v

# Bundle app source
COPY . .

EXPOSE 3000
CMD [ "node", "src/index.js" ]
